### ISSUE TITLE
Dashboard overview requirements

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-frontend#15]
# TODO

### 🗒 &nbsp; Summary

Requirements that need to be fulfilled by the "Dashboard - Overview" page.

### ✅ &nbsp; Outcomes

I (as a user) should be able to:

- [x] View the current status of my investments with some indication of how those investments are doing
       - [ ] [To be done later] Answer the question "do I need to change them for optimal returns?"

- [x] Change my selected validators without having to go through the entire payment process - i.e. "quick change" of sorts

- [x] Change my payment destination (where my rewards are being transferred to) - again "quick change"

- [x] Change the controller being used - again "quick change"

~- [ ] See claimable rewards + Claim rewards for specific or all validators~

- [x] Unbond funds - sort of "quick unbond" - i.e. not going through the entire payment process.

- [x] Bond more funds - "quick bond"

- [x] Stop all nominations - I would also want to be prompted for unbonding my funds if I click the "stop all" button

## ⏳ &nbsp; ETA

Not updated yet

If you don't specify a timezone, by default IST shall be assumed.

Refer: [ETA culture document](https://docs.google.com/document/d/1ZGa6diesOmx-jSBjm0uj8j4oN75gYqux85qA7DJOm68/edit)
