### ISSUE TITLE
[TODO] for accounts with different controller and stash accounts display warning and disable staking

### ISSUE THREAD

**Issue by sahilnanda1995** [buidl-labs/yieldscan-frontend#189]
# TODO

## 🎯 &nbsp; What is the problem that needs to be solved?

Try to be as specific as possible. Think about falsifiable outcomes.

**Refer:** [SMART Goal Examples](https://www.thebalancesmb.com/smart-goal-examples-2951827)

### 🗒 &nbsp; Summary
A brief overview of the problem to be solved. Include all relevant data points.

### ✅ &nbsp; Outcomes
**Examples:**

- [ ] Create the a functional UI for returns calculator which takes `stake_amount` as input and returns `annual_percentage_return` as output
- [ ] Add a functional risk level input to the calculator
- [ ] Add a switch input to compound returns

## ⏳ &nbsp; ETA
**Example:** By `26th June, 2020 - 6 PM IST`

If you don't specify a timezone, by default IST shall be assumed.

Refer: [ETA culture document](https://docs.google.com/document/d/1ZGa6diesOmx-jSBjm0uj8j4oN75gYqux85qA7DJOm68/edit)
