### ISSUE TITLE
[TODO] Provide endpoint for product tracking key stats

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-frontend#196]
# TODO

### 🗒 &nbsp; Summary
Provide endpoint for product tracking key stats

### ✅ &nbsp; Outcomes

- [ ] Total Bonded Volume
- [ ] Total Unbonded Volume
- [ ] Total Stake Redistribution Volume
- [ ] Number of Unique Users
- [ ] Total Current Stake Volume being managed by YieldScan

## ⏳ &nbsp; ETA
By `19th December, 2020 - EOD IST`
