### ISSUE TITLE
[TODO] sprint/week-3

### ISSUE THREAD

**Issue by akshatbhargava123** [buidl-labs/yieldscan-frontend#20]
# TODO

### Dashboard Overview
- [x] View the current status of my investments
- [x] Change my selected validators without having to go through the entire payment process - i.e. "quick change".
- [x] Change my payment destination (where my rewards are being transferred to) - again "quick change".
- [x] Change the controller being used - again "quick change".
- [x] Unbond funds - sort of "quick unbond" - i.e. not going through the entire payment process.
- [x] Bond more funds - "quick bond"
- [x] Stop all nominations - I would also want to be prompted for unbonding my funds if I click the "stop all" button
- [x] [+P1] feedback incorporation #24 
- [x] feedback iteration 2
- [x] feedback iteration 3 and 4

### Validator Profile Page
- [x] Implement Design for the page + tabs
- [x] Implement Design for Edit profile
- [x] Show key stats from API data
- [ ] Show members from API data (API not ready yet)
- [x] Implement Authentication

### Validators Table
- [ ] Validator Table multiple behaviours based on `bondedAmount` where if some amount is bonded then allow nominations only and no `bondExtra` #23 
- [ ] Validator list page working independently without needing to come from `advanced-edit` #25 

Sprint closed, leftover work shifted to the next sprint.

**Comment by akshatbhargava123** [comment]
ETA according to current awareness on these issues: tomorrow (1st July, 2020) EOD.

**Comment by akshatbhargava123** [comment]
@saumyakaran, I have a few doubts currently regarding bonding/unbonding:

1. On the bond additional funds screen, we’re showing estimated returns, how do we calculate it when we don’t have the time period?
2. On the unbond screen, we’re showing validators, why? and also the same question here as first.

**Comment by saumyakaran** [comment]
@akshatbhargava123 

1. I believe it was missed in the design - was review it just now myself as well and noticed a similar problem on suggested validators confirmation popup.

For now we can assume a default setting for the time period like monthly returns for fixed returns (i.e. the amount in KSM/DOT) and have an annual percentage return (APR) displayed on the side

2. For both screens, your returns would be affected due to change in stake amount, we want to show how each vaidator gets affected as the user changes their input

cc @AbhinavThukral97

**Comment by saumyakaran** [comment]
@akshatbhargava123 Feedback:

1. I'm unable to change nominations when my stash and controller accounts are distinct - seems like we're not checking to find the controller before making network calls (I believe stash is used as the origin account for bonding/unbonding related activities and controller is used as the origin account for changing nominations, chilling and even for changing payment destination)
![Screenshot 2020-07-03 at 10 43 07 AM](https://user-images.githubusercontent.com/40575379/86434045-03df8100-bd1a-11ea-86e7-98f4d714be2a.png)

Source: https://polkascan.io/kusama/transaction/0xcaec084c4992513775866857909bd0dcd71e0c32204a8624ff07b95537b699a0

From browser console for more info:
![Screenshot 2020-07-03 at 10 44 43 AM](https://user-images.githubusercontent.com/40575379/86434111-3a1d0080-bd1a-11ea-910c-ed4ef578f2e2.png)

When using stash instead of controller for changing nominations or payment destination or chilling the following happens:
![Screenshot 2020-07-03 at 10 58 14 AM](https://user-images.githubusercontent.com/40575379/86434893-45712b80-bd1c-11ea-8802-c11a8de2495e.png)


2. The bond additional funds input won't accept any input larger than the amount I have as free balance... While it works, it's not necessarily the best UX - I would rather be able to enter the amount, but be unable to stake + be shown an input validation error

3. Estimated monthly rewards is shown as 0 KSM - I think there's at least some amount which I would earn:
![Screenshot 2020-07-03 at 10 47 35 AM](https://user-images.githubusercontent.com/40575379/86434255-a0098800-bd1a-11ea-9426-198d0d92c66c.png)

PS - I have no info about the estimated reward for the individual validator - is it calculated for an annual or month time period? Or something else altogether?

This point 3 also applies to unbond popup and edit validators popup

4. When I open the payment destination popup, it doesn't have my current selected preference pre-filled
