### ISSUE TITLE
sprint/m2-shipment

### ISSUE THREAD

**Issue by akshatbhargava123** [buidl-labs/yieldscan-frontend#29]
# TODO

### Validator Profile Page
- [x] Show members from API data
- [x] Make edit modal functionality working

### Validators Table
- [x] Validator list page working independently without needing to come from `advanced-edit` #25 
- [x] design improvements
- [x] Add input for compounding in validator result top bar.

Points removed after discussion because changes for this are required in the long run:
- ~Validator list page dynamic design based on view type~ To be dealt in separate sprint.
- ~Validator Table multiple behaviors based on `bondedAmount` where if some amount is bonded then allow to nominate only and no `bondExtra`. #23~ To be dealt in separate sprint.

### Council members Table View - _design and functionality of the below points_
- [x] Council member table view
- [x] Council member profile view
- [x] Council member edit profile modal

### Nominators View
- [x] Design Home page view [here](https://www.figma.com/file/n65zoIVgwL847PMyerqkLx/YieldScan-v2-Designs?node-id=1326%3A10302)
- [x] functionality of home page view

---

- [x] Addition of back buttons to staking user flow, validator table (i.e. advanced selection mode), payment user flow and profile user flow (i.e. I can go back to the view which triggered redirection to the profile - example: returns calc or validator's table)
- [x] I want to be able to see validator profiles from returns calculator UI as well i.e. be redirected to it with an option to go back
- [x] I would want the profile redirection to be triggered whenever I click either the profile pic/identicon or the name of the validator
