### ISSUE TITLE
[TODO] UI/UX improvements after M3 completion

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-frontend#32]
# TODO

## 🎯 &nbsp; What is the problem that needs to be solved?

Try to be as specific as possible. Think about falsifiable outcomes.

**Refer:** [SMART Goal Examples](https://www.thebalancesmb.com/smart-goal-examples-2951827)

### 🗒 &nbsp; Summary
UI/UX changes that are important, but were deprioritized due to M2 deadline.

## Global

- [x] We need to add KSM → USD conversions at all places
- [x] We need to replace big and small numbers by appropriate units for example 10,000 KSM → 10k KSM, 0.01 KSM → 10 mKSM, 10,000,000 → 10M KSM
    - ~In some places (like key stats), the complete number might need to be displayed - in which case, we need to add commas for big numbers - for small numbers, the units with 3 decimals works well~

## Returns calculator
- [ ] [+P1 - CRITICAL] Change the flow of the calculator, validators tab and advanced validator selection for the already bonded case - i.e. treating bonding/unbonding and nominating as 2 separate steps (refer [this](https://www.figma.com/file/n65zoIVgwL847PMyerqkLx/YieldScan-v2-Designs?node-id=1717%3A20981) for design)

## Validators tab and advanced selection

- [ ] Input validation is missing in validators tab and advanced validator selection
- [ ] Search bar for filtering validators by name or address

## Payment UX
- None

## Overview tab
- None

## Nominators leaderboard

- [ ] Pagination needs to be added for both validators and nominators
    - Since the number is quite large
    - A technical problem here might be regarding sorting and filtering - if that works fine, then we should definitely implement this
- [ ] Search bar for filtering nominators by name or address

## Governance

- None

## ⏳ &nbsp; ETA
**Example:** By `26th June, 2020 - 6 PM IST`

If you don't specify a timezone, by default IST shall be assumed.

Refer: [ETA culture document](https://docs.google.com/document/d/1ZGa6diesOmx-jSBjm0uj8j4oN75gYqux85qA7DJOm68/edit)

**Comment by saumyakaran** [comment]
- [ ] In the returns calculator, although I'm able to input 0 now, it still doesn't show me suggestions if I input 0 - i.e. the case where I don't want to change my bonded amount
- [ ] Payment confirmation view doesn't have identicons for selected validators
- [ ] In the final step of the payment confirmation, placeholder image needs to be replaced with identicon of the nominator's accounts - both stash and controller
- [ ] Unsure if this is implemented or not, but after completion of transaction, user should be redirected to the overview tab (ideally the UX here should be the same as presented in the design: https://www.figma.com/file/n65zoIVgwL847PMyerqkLx/YieldScan-v2-Designs?node-id=1326%3A15523 - but given the time crunch, redirection might be a relatively easier shortcut)
