### ISSUE TITLE
[TODO] M2 Resubmission fixes

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-frontend#37]
# TODO

## 🎯 &nbsp; What is the problem that needs to be solved?

Try to be as specific as possible. Think about falsifiable outcomes.

**Refer:** [SMART Goal Examples](https://www.thebalancesmb.com/smart-goal-examples-2951827)

### 🗒 &nbsp; Summary
A brief overview of the problem to be solved. Include all relevant data points.

### ✅ &nbsp; Outcomes

- [x]  I need to fill out "bond additional funds" in order to see the results of the calculations (even if I don’t want to bond additional funds) - allow 0 as the input by default
- [x]  Update README to inform reader how to update .env file to use either our backend or host their own
    - [x]  Create the mechanism for reading variables from env file
- [x]  Implementation for info question marks as per design (dependency - design change)

## ⏳ &nbsp; ETA

TBD

If you don't specify a timezone, by default IST shall be assumed.

Refer: [ETA culture document](https://docs.google.com/document/d/1ZGa6diesOmx-jSBjm0uj8j4oN75gYqux85qA7DJOm68/edit)

**Comment by saumyakaran** [comment]
Relevant attached [here](https://buidllabs.slack.com/archives/C0113AU1XUG/p1595345507007400)

**Comment by akshatbhargava123** [comment]
PR here: https://github.com/buidl-labs/yieldscan-frontend/pull/38
