### ISSUE TITLE
[TODO] Analytics feedback (incremental changes)

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-frontend#68]
# TODO

### ✅ &nbsp; Outcomes

- [x] Transaction failure should log the error message sent by the chain even though it might not make any sense by itself because of the cryptic error index and no descriptive information
- [x] Debounce reward calculator event logging
- [x] Track intention for wallet connection

## ⏳ &nbsp; ETA

TBD

If you don't specify a timezone, by default IST shall be assumed.

Refer: [ETA culture document](https://docs.google.com/document/d/1ZGa6diesOmx-jSBjm0uj8j4oN75gYqux85qA7DJOm68/edit)
